services:
  db:
    image: postgres:15
    container_name: test-postgres-user
    environment:
      POSTGRES_DB: ${DATABASE_DBNAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./test_postgres_data:/var/lib/postgresql/data
